import { Poppins } from "next/font/google";
import "./globals.css";

// const Poppins = Poppins({
//  subsets: ["latin"],
//  weight:["100"]
// });



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${Poppins.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
